article/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from .views import ListArticle, DetailArticle, Likees, Clapes
from django.views.generic import TemplateView

app_name = "article"

urlpatterns = [
    path("", ListArticle.as_view(), name="list"),
    path("detail/<int:pk>", DetailArticle.as_view(), name="detail"),
    path("like/<int:pk>", Likees, name='like'),
    path("clap/<int:pk>", Clapes, name='clap'),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, EditView, Success

app_name = "core"
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('edit/<int:pk>', EditView.as_view(), name="update"),
    path('success/<int:pk>', Success, name="success"),
]

ppl1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('core.urls', namespace="core")),
    path('riwayat/', include("riwayat.urls", namespace="riwayat")),
    path('inspiration/', include("inspiration.urls", namespace="inspiration")),
    path('article/', include("article.urls", namespace="article")),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

# Create your models here.


class Article(models.Model):
    title = models.CharField(_("judul"), max_length=255)
    image = models.ImageField(_("gambar"), upload_to='article/', null=True)
    time = models.DateTimeField(_("waktu"), auto_now=True, auto_now_add=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, default=1)
    countLike = models.IntegerField(_("Like"), null=True)
    countClap = models.IntegerField(_("Clap"), null=True)


class Likes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, default=1)
    article = models.ForeignKey(
        Article,  on_delete=models.CASCADE, default=1)


class Claps(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, default=1)
    article = models.ForeignKey(
        Article,  on_delete=models.CASCADE, default=1)

article/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Article, Likes, Claps
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ListArticle(LoginRequiredMixin, ListView):
    template_name = "article/list.html"
    ordering = ['-time']
    model = Article
    paginate_by = 2

    def post(self, request, *args, **kwargs):
        title = request.POST.get("title")
        try:
            if request.FILES['image']:
                myfile = request.FILES['image']
                fs = FileSystemStorage()
                filename = fs.save("article/"+myfile.name, myfile)
                article = Article.objects.create(
                    title=title, image=filename, user=request.user, countLike=0, countClap=0)
        except KeyError:
            article = Article.objects.create(
                title=title, user=request.user, countLike=0, countClap=0)
        article.save()
        return redirect('article:list')

    def get_queryset(self):
        try:
            print(self.request.GET.get('search'))
            self.queryset = self.model.objects.filter(
                title__icontains=self.request.GET['search'])
        except KeyError:
            pass
        return super().get_queryset()


class DetailArticle(LoginRequiredMixin, DetailView):
    template_name = "article/detail.html"
    model = Article


def Likees(request, *args, **kwargs):
    tarticle = Article.objects.get(id=kwargs['pk'])
    if Likes.objects.filter(user=request.user, article=kwargs['pk']).count() != 1:
        like = Likes(user=request.user, article=tarticle)
        like.save()
        Article.objects.filter(id=kwargs['pk']).update(
            countLike=(tarticle.countLike+1))
    return redirect("article:list")


def Clapes(request, *args, **kwargs):
    tarticle = Article.objects.get(id=kwargs['pk'])
    if Claps.objects.filter(user=request.user, article=kwargs['pk']).count() != 1:
        clap = Claps(user=request.user, article=tarticle)
        clap.save()
        Article.objects.filter(id=kwargs['pk']).update(
            countClap=(tarticle.countClap+1))
    return redirect("article:list")

article/templates/article/detail.html
{{object.title}}
{{object.description}}
<img src="/media/{{object.image}}" width="100px" height="100px">
{{object.time}}

article/templates/article/list.html
{% extends 'argon/base.html' %}
{% block topnav %}
<!-- Topnav -->
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Search form -->
            <form action="{% url 'article:list'  %}" method="GET"
                class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                {% csrf_token %}
                <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-search"></i></span>
                        </div>
                        <input class="form-control" placeholder="Search" name="search" type="text">
                    </div>
                </div>
                <button type="button" class="close" data-action="search-close" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </form>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                        data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>

            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="Image placeholder" src="/media/{{request.user.avatar}}">
                            </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{request.user.name}}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>

                        <a href="{% url 'core:update' request.user.id %}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>Edit Profil</span>
                        </a>
                        <a href="{% url 'index' %}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock topnav %}
{% block content %}
<div class="card">
    <div class="row">
        <div class=" col-md-1 text-center">
            <span class="avatar avatar-sm rounded-circle mt-3 ml-2">
                <img alt="Image placeholder" src="/media/{{request.user.avatar}}">
            </span>
        </div>
        <form action="" method="POST" enctype="multipart/form-data" class="col-md-11">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-10 pt-2">
                    <div class="form-group ">
                        <input type="text" name="title" class="form-control" placeholder="Ayo mulai berbagi status"
                            aria-label="Username" aria-describedby="basic-addon1" style="border:none;box-shadow:none;">
                    </div>
                </div>
                <div class="col-md-2 pt-3">
                    <div class="form-group">
                        <label for="submit" class="mr-2"><i class='fa fa-paper-plane'
                                style="font-size: 24px; cursor:pointer;"></i></label>
                        <button type="submit" id="submit" style="display:none"></button>
                        <label for="image"><i class='fa fa-camera' style="font-size: 24px; cursor:pointer;"></i></label>
                        <input type="file" id="image" name="image" style="display:none">
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% for info in object_list %}
<div class="card">
    <div class="row">
        <div class="col-md-1 text-center">
            <span class="avatar avatar-sm rounded-circle mt-3 ml-2">
                <img alt="Image placeholder" src="/media/{{info.user.avatar}}">
            </span>
        </div>
        <div class="col-md-11 pt-2">
            <span class="row">
                {{info.user.name}}
            </span>
            <span class="row">
                <i class="fa fa-clock mr-1 mt-1" style="font-size:18px"></i>
                {{info.time}}
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 pt-2 pl-4">
            {{info.title}}
        </div>
    </div>
    {% if info.image %}
    <div class="row">
        <div class="col-md-12 pt-2 pl-4">
            <img alt="Image" src="/media/{{info.image}}" widht="200px" height="200px">
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-12 pl-4 pt-4 pb-2">
            <a href="{% url 'article:like' info.id %}" class="ml-2">
                <i class="fa fa-thumbs-up" style="font-size: 20px;"></i>
                {{info.countLike}} likes
            </a>
            <a href="{% url 'article:clap' info.id %}" class="ml-2"><i class="fa fa-hand-paper"
                    style="font-size: 20px;"></i>
                {{info.countClap}} claps
            </a>
        </div>
    </div>
</div>
{% endfor %}

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination" style="justify-content: center;">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                <i class="fa fa-angle-left"></i>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <i class="fa fa-angle-right"></i>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}