core/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, EditView, Success

app_name = "core"
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('edit/<int:pk>', EditView.as_view(), name="update"),
    path('success/<int:pk>', Success, name="success"),
]

ppl1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('core.urls', namespace="core")),
    path('riwayat/', include("riwayat.urls", namespace="riwayat")),
    path('inspiration/', include("inspiration.urls", namespace="inspiration")),
    path('article/', include("article.urls", namespace="article")),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

riwayat/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from .views import CreateRiwayat, ListRiwayat, UpdateRiwayat

app_name = "riwayat"

urlpatterns = [
    path('create', CreateRiwayat.as_view(), name='create'),
    path("", ListRiwayat.as_view(), name="list"),
    path("update/<int:pk>", UpdateRiwayat.as_view(), name="update"),
]

riwayat/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.conf import settings

# Create your models here.


class Riwayat (models.Model):
    title = models.CharField(_("judul"), max_length=100)
    description = models.TextField(_("deskripsi"))
    image = models.ImageField(_("gambar"), upload_to='riwayat')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, default=1)
    time = models.DateTimeField(_("waktu"), auto_now=False, auto_now_add=False)

    def get_absolute_url(self):
        return reverse("riwayat:list")

riwayat/forms.py
from django import forms
from .models import Riwayat


class RiwayatForm(forms.ModelForm):
    class Meta:
        model = Riwayat
        fields = ['title', 'description', 'time', 'image']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': 'Masukkan title anda'
                }
            ),
            'description': forms.TextInput(
                attrs={
                    'class': 'form-control mb-2',
                    'placeholder': 'Masukkan description anda'
                }
            ),
            'time': forms.TextInput(
                attrs={
                    'type': 'date',
                    'class': 'form-control mb-2',
                }
            ),
        }

riwayat/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView
from .models import Riwayat
from .forms import RiwayatForm
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class CreateRiwayat(LoginRequiredMixin, CreateView):
    form_class = RiwayatForm
    template_name = 'riwayat/create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ListRiwayat(LoginRequiredMixin, ListView):
    model = Riwayat
    paginate_by = 3
    ordering = ['-time']
    template_name = 'riwayat/list.html'

def get_queryset(self):
    self.queryset = self.model.objects.filter(user=self.request.user)
    return super().get_queryset()

class UpdateRiwayat(LoginRequiredMixin, UpdateView):
    form_class = RiwayatForm
    model = Riwayat
    template_name = 'riwayat/create.html'

riwayat/templates/riwayat/create.html
{% extends 'argon/base.html' %}

{% block content %}
<form method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <div class="card" style="padding:2em">
        {{form.title}}
        <span class="text-danger">
            {{form.title.errors}}
        </span>
        {{form.description}}
        <span class="text-danger">
            {{form.description.errors}}
        </span>
        {{form.time}}
        <span class="text-danger">
            {{form.time.errors}}
        </span>

        <div class="custom-file">
            {{form.image}}
            <label class="custom-file-label" for="id_image">Select file</label>
            <span class="text-danger">
                {{form.image.errors}}
            </span>

        </div>
    </div>
    <div class="create-riwayat">
        <label for="submit" style="cursor:pointer;"><i class="fa fa-plus"></i></label>
        <button type="submit" style="display:none;" id="submit"></button>
    </div>
</form>
{% endblock content %}

riwayat/templates/riwayat/list.html
{% extends 'argon/base.html' %}

{% block content %}
{% for info in object_list %}
<div class="card">
    <div class="row">
        <div class="col-md-10 pl-4" style="font-size:24px">{{info.title}}</div>
        <div class="col-md-2 pr-2" style="font-size:12px">
            {{info.time|date}}
            <a href="{% url 'riwayat:update' info.id %}">
                <i class="fa fa-edit ml-2"></i>
            </a>
        </div>
    </div>
    <div class="row pb-2">
        <div class="col-md-3 pl-4">
            <img src="/media/{{info.image}}" width="200px" height="200px" alt="">
        </div>
        <div class="col-md-9">
            {{info.description}}
        </div>
    </div>
</div>
{% empty %}
<div class="card">
    <div class="row">
        <div class="col-md-10 pl-4" style="font-size:24px">Data Kosong</div>
    </div>
    <div class="row pb-2">
        <div class="col-md-9">
            Data Kosong
        </div>
    </div>
</div>
{% endfor %}

{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination" style="justify-content: center;">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                <i class="fa fa-angle-left"></i>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <i class="fa fa-angle-right"></i>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

<div class="create-riwayat">
    <a href="{% url 'riwayat:create' %}">
        <i class="fa fa-plus"></i>
    </a>
</div>
{% endblock content %}