core/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, EditView, Success

app_name = "core"
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('edit/<int:pk>', EditView.as_view(), name="update"),
    path('success/<int:pk>', Success, name="success"),
]

ppl1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('core.urls', namespace="core")),
    path('riwayat/', include("riwayat.urls", namespace="riwayat")),
    path('inspiration/', include("inspiration.urls", namespace="inspiration")),
    path('article/', include("article.urls", namespace="article")),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/wrap/banner.html
<div class="container">
    <div class="row mt-5 d-flex justify-content-center">
        <div class="col-md-8 text-center heading-section ftco-animate">
            <h2 class="h1">Kita berbeda, <strong class="px-3">bukan berarti buruk.</strong> Berani Beda Itu HEBAT dan
                Lebih
                Baik</h2>
            <h3 class="h2">Ayo, bersama-sama dalam meraih cita dan asa dengan berbagi kekuatan sambil berpegang tangan.
            </h3>
            <h5><strong class="px-3">Untuk membuktikan kehebatan kita kepada dunia</strong></h5>
            <p><a href="#" class="btn btn-primary mt-3 py-3 px-5">Get in touch</a></p>
        </div>
    </div>
</div>

templates/wrap/footer.html
<footer class="text-center container">
    <p>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>
            document.write(new Date().getFullYear());
        </script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a
            href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    </p>
</footer>

templates/wrap/header.html
{% load static %}
<title>{{page}}</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css?family=Work+Sans:100,200,300,400,700,800" rel="stylesheet">

<link rel="stylesheet" href="{% static 'landing/css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/animate.css' %}">

<link rel="stylesheet" href="{% static 'landing/css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'landing/css/aos.css' %}">

<link rel="stylesheet" href="{% static 'landing/css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'landing/css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/jquery.timepicker.css' %}">


<link rel="stylesheet" href="{% static 'landing/css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'landing/css/style.css' %}">

<style type="text/css">
    body {
        background-image: url("{% static 'landing/images/image_5.png' %}");
        background-repeat: no-repeat;
        background-size: 40% 35%;
        background-size: cover;
    }
</style>

templates/wrap/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="index.html">lingkaranHebat.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
            aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'core:login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'core:register' %}" class="nav-link">Register</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/wrap/script.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
</script>
<script src="{% static 'landing/js/jquery.min.js' %}"></script>
<script src="{% static 'landing/js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'landing/js/popper.min.js' %}"></script>
<script src="{% static 'landing/js/bootstrap.min.js' %}"></script>
<script src="{% static 'landing/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'landing/js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'landing/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'landing/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'landing/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'landing/js/aos.js' %}"></script>
<script src="{% static 'landing/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'landing/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'landing/js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'landing/js/particles.min.js' %}"></script>
<script src="{% static 'landing/js/particle.js' %}"></script>
<script src="{% static 'landing/js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false">
</script>
<script src="{% static 'landing/js/google-map.js' %}"></script>
<script src="{% static 'landing/js/main.js' %}"></script>

<script>
    $('input[type="button"]').on('click', function () {
        $('input[type="button"]').removeClass('btn-warning');
        $(this).toggleClass('btn-warning');
    });

    const navbar = document.getElementById("ftco-navbar")
    window.addEventListener('load', res => {

        navbar.classList.add("scrolled")
    });
    window.addEventListener('scroll', res => {
        navbar.classList.remove("scrolled")
        navbar.classList.add("scrolled")

    });
    $('.custom-file-input').on('change', function () {
        let filename = $(this).val().split('\\').pop();
        $(this).next('.custom-file-label').addClass("selected").html(filename);
    });
</script>