article/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from .views import ListArticle, DetailArticle, Likees, Clapes
from django.views.generic import TemplateView

app_name = "article"

urlpatterns = [
    path("", ListArticle.as_view(), name="list"),
    path("detail/<int:pk>", DetailArticle.as_view(), name="detail"),
    path("like/<int:pk>", Likees, name='like'),
    path("clap/<int:pk>", Clapes, name='clap'),
]

core/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, EditView, Success

app_name = "core"
urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='auth/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('edit/<int:pk>', EditView.as_view(), name="update"),
    path('success/<int:pk>', Success, name="success"),
]

ppl1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('core.urls', namespace="core")),
    path('riwayat/', include("riwayat.urls", namespace="riwayat")),
    path('inspiration/', include("inspiration.urls", namespace="inspiration")),
    path('article/', include("article.urls", namespace="article")),
    path('', TemplateView.as_view(template_name="index.html"), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/argon/wrap/footer.html
<!-- Footer -->
<footer class="footer pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
            <div class="copyright text-center  text-lg-left  text-muted">
                &copy; 2020 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1"
                    target="_blank">Kelompok PPL</a>
            </div>
        </div>
        <div class="col-lg-6">
            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                    <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                    <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                    <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md"
                        class="nav-link" target="_blank">MIT License</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

templates/argon/wrap/header.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
<meta name="author" content="Creative Tim">
<title>{{page}}</title>
<!-- Favicon -->
<link rel="icon" href="{% static 'img/brand/favicon.png' %}" type="image/png">
<!-- Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
<!-- Icons -->
<link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %} " type="text/css">
<link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %} " type="text/css">
<!-- Page plugins -->
<!-- Argon CSS -->
<link rel="stylesheet" href="{% static 'css/argon.css' %}?v=1.2.0" type="text/css">
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

templates/argon/wrap/script.html
{% load static %}

<!-- Argon Scripts -->
<!-- Core -->
<script src="{% static 'vendor/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/js-cookie/js.cookie.js' %}"></script>
<script src="{% static 'vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
<!-- Optional JS -->
<script src="{% static 'vendor/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'vendor/chart.js/dist/Chart.extension.js' %}"></script>
<!-- Argon JS -->
<script src="{% static 'js/argon.js' %}?v=1.2.0"></script>
<script src="{% static 'js/file.js' %}"></script>

templates/argon/wrap/sidenav.html
<!-- Sidenav -->
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <a class="navbar-brand" href="javascript:void(0)">
                <img src="/static/img/brand/blue.png" class="navbar-brand-img" alt="...">
            </a>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    {% comment %} <li class="nav-item">
                        <a class="nav-link active" href="{% url 'index' %}">
                            <i class="fas fa-home"></i>
                            <span class="nav-link-text">Home</span>
                        </a>
                    </li> {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'riwayat:list' %}">
                            <i class="ni ni-collection text-primary"></i>
                            <span class="nav-link-text">Treatment</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'inspiration:list' %}">
                            <i class="ni ni-pin-3 text-primary"></i>
                            <span class="nav-link-text">Inspiration</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'article:list' %}">
                            <i class="ni ni-single-02"></i>
                            <span class="nav-link-text">Article</span>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</nav>

templates/argon/wrap/topnav.html
<!-- Topnav -->
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Search form -->
            <form action="{% url 'inspiration:list'  %}" method="GET"
                class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                {% csrf_token %}
                <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-search"></i></span>
                        </div>
                        <input class="form-control" placeholder="Search" name="search" type="text">
                    </div>
                </div>
                <button type="button" class="close" data-action="search-close" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </form>
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                        data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>

            </ul>
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                        <div class="media align-items-center">
                            <span class="avatar avatar-sm rounded-circle">
                                <img alt="Image placeholder" src="/media/{{request.user.avatar}}">
                            </span>
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{request.user.name}}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>

                        <a href="{% url 'core:update' request.user.id %}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>Edit Profil</span>
                        </a>
                        <a href="{% url 'index' %}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>